ALTER TABLE tasks ADD COLUMN IF NOT EXISTS work_rest_ratio VARCHAR(30) DEFAULT 'CONTINUOUS';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS cooling_measures TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS mitigation_notes TEXT;
